BASE_URL = "https://play.fifa.com/json/fantasy/"

team_strength = {
    "France": 10.0,
    "Spain": 9.7,
    "Argentina": 9.6,
    "England": 9.2,
    "Brazil": 9.1,
    "Portugal": 9.0,
    "Netherlands": 8.4,
    "Germany": 8.3,
    "Belgium": 8.0,
    "Morocco": 7.8,
    "Croatia": 7.7,
    "Colombia": 7.2,
    "Uruguay": 7.1,
    "Japan": 6.9,
    "Switzerland": 6.8,
    "Senegal": 6.7,
    "Mexico": 6.4,
    "United States": 6.2,
    "South Korea": 6.0,
    "Ecuador": 5.9,
    "Austria": 5.8,
    "Iran": 5.6,
    "Norway": 5.6,
    "Australia": 5.3,
    "Egypt": 5.2,
    "Türkiye": 5.1,
    "Ivory Coast": 5.0,
    "Sweden": 5.0,
    "Canada": 4.9,
    "Scotland": 4.7,
    "Algeria": 4.6,
    "Qatar": 4.4,
    "Czechia": 4.4,
    "Paraguay": 4.2,
    "Tunisia": 4.1,
    "Bosnia & Herzegovina": 4.0,
    "Ghana": 3.9,
    "DR Congo": 3.7,
    "South Africa": 3.6,
    "Saudi Arabia": 3.5,
    "Panama": 3.4,
    "Iraq": 3.2,
    "Uzbekistan": 3.0,
    "Cape Verde": 2.8,
    "Jordan": 2.7,
    "Haiti": 2.4,
    "New Zealand": 2.3,
    "Curaçao": 2.0,
}
